# Generated by Django 3.2.6 on 2023-12-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0002_secondpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title3', models.CharField(max_length=250)),
                ('content3', models.TextField()),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
