# Generated by Django 3.2.6 on 2023-12-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0003_tercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
