# Generated by Django 3.2.6 on 2023-12-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0004_alter_tercero_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tercero',
            name='numero',
        ),
    ]
